# http://search.cpan.org/dist/CPAN-Meta/lib/CPAN/Meta/Spec.pm
name:         URI-tel
version:      0.1
version_from: lib/URI/tel.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 7.18
